### ISSUE TITLE
Complete `meta` of problems

### ISSUE THREAD

**Issue by tmigot** [tmigot/PDEOptimizationProblems#4]
- [ ] size of `incompressibleNavierStokes`
- [ ] `deriv` of `glider`, `methanol`, `minsurf`, `rocket`, `poissonboltzman2d`
- [ ] `optimal_value` (compare with results from COPS)
- [ ] `is_infeasible`
- [ ] `origin`
- [ ] `has_cvx_obj`, `has_cvx_con`
